const m = {
  ez: { type: 'application/andrew-inset', charset: null },
  appinstaller: { type: 'application/appinstaller', charset: null },
  aw: { type: 'application/applixware', charset: null },
  appx: { type: 'application/appx', charset: null },
  appxbundle: { type: 'application/appxbundle', charset: null },
  atom: { type: 'application/atom+xml', charset: null },
  atomcat: { type: 'application/atomcat+xml', charset: null },
  atomdeleted: { type: 'application/atomdeleted+xml', charset: null },
  atomsvc: { type: 'application/atomsvc+xml', charset: null },
  dwd: { type: 'application/atsc-dwd+xml', charset: null },
  held: { type: 'application/atsc-held+xml', charset: null },
  rsat: { type: 'application/atsc-rsat+xml', charset: null },
  aml: { type: 'application/automationml-aml+xml', charset: null },
  amlx: { type: 'application/automationml-amlx+zip', charset: null },
  bdoc: { type: 'application/bdoc', charset: null },
  xcs: { type: 'application/calendar+xml', charset: null },
  ccxml: { type: 'application/ccxml+xml', charset: null },
  cdfx: { type: 'application/cdfx+xml', charset: null },
  cdmia: { type: 'application/cdmi-capability', charset: null },
  cdmic: { type: 'application/cdmi-container', charset: null },
  cdmid: { type: 'application/cdmi-domain', charset: null },
  cdmio: { type: 'application/cdmi-object', charset: null },
  cdmiq: { type: 'application/cdmi-queue', charset: null },
  cpl: { type: 'application/cpl+xml', charset: null },
  cu: { type: 'application/cu-seeme', charset: null },
  cwl: { type: 'application/cwl', charset: null },
  mpd: { type: 'application/dash+xml', charset: null },
  mpp: { type: 'application/dash-patch+xml', charset: null },
  davmount: { type: 'application/davmount+xml', charset: null },
  dcm: { type: 'application/dicom', charset: null },
  dbk: { type: 'application/docbook+xml', charset: null },
  dssc: { type: 'application/dssc+der', charset: null },
  xdssc: { type: 'application/dssc+xml', charset: null },
  ecma: { type: 'application/ecmascript', charset: null },
  emma: { type: 'application/emma+xml', charset: null },
  emotionml: { type: 'application/emotionml+xml', charset: null },
  epub: { type: 'application/epub+zip', charset: null },
  exi: { type: 'application/exi', charset: null },
  exp: { type: 'application/express', charset: null },
  fdf: { type: 'application/fdf', charset: null },
  fdt: { type: 'application/fdt+xml', charset: null },
  pfr: { type: 'application/font-tdpfr', charset: null },
  geojson: { type: 'application/geo+json', charset: null },
  gml: { type: 'application/gml+xml', charset: null },
  gpx: { type: 'application/gpx+xml', charset: null },
  gxf: { type: 'application/gxf', charset: null },
  gz: { type: 'application/gzip', charset: null },
  hjson: { type: 'application/hjson', charset: null },
  stk: { type: 'application/hyperstudio', charset: null },
  ink: { type: 'application/inkml+xml', charset: null },
  inkml: null,
  ipfix: { type: 'application/ipfix', charset: null },
  its: { type: 'application/its+xml', charset: null },
  jar: { type: 'application/java-archive', charset: null },
  war: null,
  ear: null,
  ser: { type: 'application/java-serialized-object', charset: null },
  class: { type: 'application/java-vm', charset: null },
  js: { type: 'application/javascript', charset: 'utf-8' },
  json: { type: 'application/json', charset: 'utf-8' },
  map: null,
  json5: { type: 'application/json5', charset: null },
  jsonml: { type: 'application/jsonml+json', charset: null },
  jsonld: { type: 'application/ld+json', charset: null },
  lgr: { type: 'application/lgr+xml', charset: null },
  lostxml: { type: 'application/lost+xml', charset: null },
  hqx: { type: 'application/mac-binhex40', charset: null },
  cpt: { type: 'application/mac-compactpro', charset: null },
  mads: { type: 'application/mads+xml', charset: null },
  webmanifest: { type: 'application/manifest+json', charset: 'utf-8' },
  mrc: { type: 'application/marc', charset: null },
  mrcx: { type: 'application/marcxml+xml', charset: null },
  ma: { type: 'application/mathematica', charset: null },
  nb: null,
  mb: null,
  mathml: { type: 'application/mathml+xml', charset: null },
  mbox: { type: 'application/mbox', charset: null },
  mpf: { type: 'application/media-policy-dataset+xml', charset: null },
  mscml: { type: 'application/mediaservercontrol+xml', charset: null },
  metalink: { type: 'application/metalink+xml', charset: null },
  meta4: { type: 'application/metalink4+xml', charset: null },
  mets: { type: 'application/mets+xml', charset: null },
  maei: { type: 'application/mmt-aei+xml', charset: null },
  musd: { type: 'application/mmt-usd+xml', charset: null },
  mods: { type: 'application/mods+xml', charset: null },
  m21: { type: 'application/mp21', charset: null },
  mp21: null,
  mp4: { type: 'video/mp4', charset: null },
  mpg4: null,
  mp4s: null,
  m4p: null,
  msix: { type: 'application/msix', charset: null },
  msixbundle: { type: 'application/msixbundle', charset: null },
  doc: { type: 'application/msword', charset: null },
  dot: null,
  mxf: { type: 'application/mxf', charset: null },
  nq: { type: 'application/n-quads', charset: null },
  nt: { type: 'application/n-triples', charset: null },
  cjs: { type: 'application/javascript', charset: 'utf-8' },
  bin: { type: 'application/octet-stream', charset: null },
  dms: null,
  lrf: null,
  mar: null,
  so: null,
  dist: null,
  distz: null,
  pkg: null,
  bpk: null,
  dump: null,
  elc: null,
  deploy: null,
  exe: null,
  dll: null,
  deb: null,
  dmg: null,
  iso: null,
  img: null,
  msi: null,
  msp: null,
  msm: null,
  buffer: null,
  oda: { type: 'application/oda', charset: null },
  opf: { type: 'application/oebps-package+xml', charset: null },
  ogx: { type: 'application/ogg', charset: null },
  omdoc: { type: 'application/omdoc+xml', charset: null },
  onetoc: { type: 'application/onenote', charset: null },
  onetoc2: null,
  onetmp: null,
  onepkg: null,
  one: null,
  onea: null,
  oxps: { type: 'application/oxps', charset: null },
  relo: { type: 'application/p2p-overlay+xml', charset: null },
  xer: { type: 'application/patch-ops-error+xml', charset: null },
  pdf: { type: 'application/pdf', charset: null },
  pgp: { type: 'application/pgp-encrypted', charset: null },
  asc: { type: 'application/pgp-keys', charset: null },
  sig: { type: 'application/pgp-signature', charset: null },
  prf: { type: 'application/pics-rules', charset: null },
  p10: { type: 'application/pkcs10', charset: null },
  p7m: { type: 'application/pkcs7-mime', charset: null },
  p7c: null,
  p7s: { type: 'application/pkcs7-signature', charset: null },
  p8: { type: 'application/pkcs8', charset: null },
  ac: { type: 'application/pkix-attr-cert', charset: null },
  cer: { type: 'application/pkix-cert', charset: null },
  crl: { type: 'application/pkix-crl', charset: null },
  pkipath: { type: 'application/pkix-pkipath', charset: null },
  pki: { type: 'application/pkixcmp', charset: null },
  pls: { type: 'application/pls+xml', charset: null },
  ai: { type: 'application/postscript', charset: null },
  eps: null,
  ps: null,
  provx: { type: 'application/provenance+xml', charset: null },
  cww: { type: 'application/prs.cww', charset: null },
  xsf: { type: 'application/prs.xsf+xml', charset: null },
  pskcxml: { type: 'application/pskc+xml', charset: null },
  raml: { type: 'application/raml+yaml', charset: null },
  rdf: { type: 'application/rdf+xml', charset: null },
  owl: null,
  rif: { type: 'application/reginfo+xml', charset: null },
  rnc: { type: 'application/relax-ng-compact-syntax', charset: null },
  rl: { type: 'application/resource-lists+xml', charset: null },
  rld: { type: 'application/resource-lists-diff+xml', charset: null },
  rs: { type: 'application/rls-services+xml', charset: null },
  rapd: { type: 'application/route-apd+xml', charset: null },
  sls: { type: 'application/route-s-tsid+xml', charset: null },
  rusd: { type: 'application/route-usd+xml', charset: null },
  gbr: { type: 'application/rpki-ghostbusters', charset: null },
  mft: { type: 'application/rpki-manifest', charset: null },
  roa: { type: 'application/rpki-roa', charset: null },
  rsd: { type: 'application/rsd+xml', charset: null },
  rss: { type: 'application/rss+xml', charset: null },
  rtf: { type: 'application/rtf', charset: null },
  sbml: { type: 'application/sbml+xml', charset: null },
  scq: { type: 'application/scvp-cv-request', charset: null },
  scs: { type: 'application/scvp-cv-response', charset: null },
  spq: { type: 'application/scvp-vp-request', charset: null },
  spp: { type: 'application/scvp-vp-response', charset: null },
  sdp: { type: 'application/sdp', charset: null },
  senmlx: { type: 'application/senml+xml', charset: null },
  sensmlx: { type: 'application/sensml+xml', charset: null },
  setpay: { type: 'application/set-payment-initiation', charset: null },
  setreg: { type: 'application/set-registration-initiation', charset: null },
  shf: { type: 'application/shf+xml', charset: null },
  siv: { type: 'application/sieve', charset: null },
  sieve: null,
  smi: { type: 'application/smil+xml', charset: null },
  smil: null,
  rq: { type: 'application/sparql-query', charset: null },
  srx: { type: 'application/sparql-results+xml', charset: null },
  sql: { type: 'application/sql', charset: null },
  gram: { type: 'application/srgs', charset: null },
  grxml: { type: 'application/srgs+xml', charset: null },
  sru: { type: 'application/sru+xml', charset: null },
  ssdl: { type: 'application/ssdl+xml', charset: null },
  ssml: { type: 'application/ssml+xml', charset: null },
  swidtag: { type: 'application/swid+xml', charset: null },
  tei: { type: 'application/tei+xml', charset: null },
  teicorpus: null,
  tfi: { type: 'application/thraud+xml', charset: null },
  tsd: { type: 'application/timestamped-data', charset: null },
  toml: { type: 'application/toml', charset: null },
  trig: { type: 'application/trig', charset: null },
  ttml: { type: 'application/ttml+xml', charset: null },
  ubj: { type: 'application/ubjson', charset: null },
  rsheet: { type: 'application/urc-ressheet+xml', charset: null },
  td: { type: 'application/urc-targetdesc+xml', charset: null },
  '1km': { type: 'application/vnd.1000minds.decision-model+xml', charset: null },
  plb: { type: 'application/vnd.3gpp.pic-bw-large', charset: null },
  psb: { type: 'application/vnd.3gpp.pic-bw-small', charset: null },
  pvb: { type: 'application/vnd.3gpp.pic-bw-var', charset: null },
  tcap: { type: 'application/vnd.3gpp2.tcap', charset: null },
  pwn: { type: 'application/vnd.3m.post-it-notes', charset: null },
  aso: { type: 'application/vnd.accpac.simply.aso', charset: null },
  imp: { type: 'application/vnd.accpac.simply.imp', charset: null },
  acu: { type: 'application/vnd.acucobol', charset: null },
  atc: { type: 'application/vnd.acucorp', charset: null },
  acutc: null,
  air: { type: 'application/vnd.adobe.air-application-installer-package+zip', charset: null },
  fcdt: { type: 'application/vnd.adobe.formscentral.fcdt', charset: null },
  fxp: { type: 'application/vnd.adobe.fxp', charset: null },
  fxpl: null,
  xdp: { type: 'application/vnd.adobe.xdp+xml', charset: null },
  xfdf: { type: 'application/vnd.adobe.xfdf', charset: null },
  age: { type: 'application/vnd.age', charset: null },
  ahead: { type: 'application/vnd.ahead.space', charset: null },
  azf: { type: 'application/vnd.airzip.filesecure.azf', charset: null },
  azs: { type: 'application/vnd.airzip.filesecure.azs', charset: null },
  azw: { type: 'application/vnd.amazon.ebook', charset: null },
  acc: { type: 'application/vnd.americandynamics.acc', charset: null },
  ami: { type: 'application/vnd.amiga.ami', charset: null },
  apk: { type: 'application/vnd.android.package-archive', charset: null },
  cii: { type: 'application/vnd.anser-web-certificate-issue-initiation', charset: null },
  fti: { type: 'application/vnd.anser-web-funds-transfer-initiation', charset: null },
  atx: { type: 'application/vnd.antix.game-component', charset: null },
  mpkg: { type: 'application/vnd.apple.installer+xml', charset: null },
  key: { type: 'application/vnd.apple.keynote', charset: null },
  m3u8: { type: 'application/vnd.apple.mpegurl', charset: null },
  numbers: { type: 'application/vnd.apple.numbers', charset: null },
  pages: { type: 'application/vnd.apple.pages', charset: null },
  pkpass: { type: 'application/vnd.apple.pkpass', charset: null },
  swi: { type: 'application/vnd.aristanetworks.swi', charset: null },
  iota: { type: 'application/vnd.astraea-software.iota', charset: null },
  aep: { type: 'application/vnd.audiograph', charset: null },
  fbx: { type: 'application/vnd.autodesk.fbx', charset: null },
  bmml: { type: 'application/vnd.balsamiq.bmml+xml', charset: null },
  mpm: { type: 'application/vnd.blueice.multipass', charset: null },
  bmi: { type: 'application/vnd.bmi', charset: null },
  rep: { type: 'application/vnd.businessobjects', charset: null },
  cdxml: { type: 'application/vnd.chemdraw+xml', charset: null },
  mmd: { type: 'application/vnd.chipnuts.karaoke-mmd', charset: null },
  cdy: { type: 'application/vnd.cinderella', charset: null },
  csl: { type: 'application/vnd.citationstyles.style+xml', charset: null },
  cla: { type: 'application/vnd.claymore', charset: null },
  rp9: { type: 'application/vnd.cloanto.rp9', charset: null },
  c4g: { type: 'application/vnd.clonk.c4group', charset: null },
  c4d: null,
  c4f: null,
  c4p: null,
  c4u: null,
  c11amc: { type: 'application/vnd.cluetrust.cartomobile-config', charset: null },
  c11amz: { type: 'application/vnd.cluetrust.cartomobile-config-pkg', charset: null },
  csp: { type: 'application/vnd.commonspace', charset: null },
  cdbcmsg: { type: 'application/vnd.contact.cmsg', charset: null },
  cmc: { type: 'application/vnd.cosmocaller', charset: null },
  clkx: { type: 'application/vnd.crick.clicker', charset: null },
  clkk: { type: 'application/vnd.crick.clicker.keyboard', charset: null },
  clkp: { type: 'application/vnd.crick.clicker.palette', charset: null },
  clkt: { type: 'application/vnd.crick.clicker.template', charset: null },
  clkw: { type: 'application/vnd.crick.clicker.wordbank', charset: null },
  wbs: { type: 'application/vnd.criticaltools.wbs+xml', charset: null },
  pml: { type: 'application/vnd.ctc-posml', charset: null },
  ppd: { type: 'application/vnd.cups-ppd', charset: null },
  car: { type: 'application/vnd.curl.car', charset: null },
  pcurl: { type: 'application/vnd.curl.pcurl', charset: null },
  dart: { type: 'application/vnd.dart', charset: null },
  rdz: { type: 'application/vnd.data-vision.rdz', charset: null },
  dbf: { type: 'application/vnd.dbf', charset: null },
  dcmp: { type: 'application/vnd.dcmp+xml', charset: null },
  uvf: { type: 'application/vnd.dece.data', charset: null },
  uvvf: null,
  uvd: null,
  uvvd: null,
  uvt: { type: 'application/vnd.dece.ttml+xml', charset: null },
  uvvt: null,
  uvx: { type: 'application/vnd.dece.unspecified', charset: null },
  uvvx: null,
  uvz: { type: 'application/vnd.dece.zip', charset: null },
  uvvz: null,
  fe_launch: { type: 'application/vnd.denovo.fcselayout-link', charset: null },
  dna: { type: 'application/vnd.dna', charset: null },
  mlp: { type: 'application/vnd.dolby.mlp', charset: null },
  dpg: { type: 'application/vnd.dpgraph', charset: null },
  dfac: { type: 'application/vnd.dreamfactory', charset: null },
  kpxx: { type: 'application/vnd.ds-keypoint', charset: null },
  ait: { type: 'application/vnd.dvb.ait', charset: null },
  svc: { type: 'application/vnd.dvb.service', charset: null },
  geo: { type: 'application/vnd.dynageo', charset: null },
  mag: { type: 'application/vnd.ecowin.chart', charset: null },
  nml: { type: 'application/vnd.enliven', charset: null },
  esf: { type: 'application/vnd.epson.esf', charset: null },
  msf: { type: 'application/vnd.epson.msf', charset: null },
  qam: { type: 'application/vnd.epson.quickanime', charset: null },
  slt: { type: 'application/vnd.epson.salt', charset: null },
  ssf: { type: 'application/vnd.epson.ssf', charset: null },
  es3: { type: 'application/vnd.eszigno3+xml', charset: null },
  et3: null,
  ez2: { type: 'application/vnd.ezpix-album', charset: null },
  ez3: { type: 'application/vnd.ezpix-package', charset: null },
  mseed: { type: 'application/vnd.fdsn.mseed', charset: null },
  seed: { type: 'application/vnd.fdsn.seed', charset: null },
  dataless: null,
  gph: { type: 'application/vnd.flographit', charset: null },
  ftc: { type: 'application/vnd.fluxtime.clip', charset: null },
  fm: { type: 'application/vnd.framemaker', charset: null },
  frame: null,
  maker: null,
  book: null,
  fnc: { type: 'application/vnd.frogans.fnc', charset: null },
  ltf: { type: 'application/vnd.frogans.ltf', charset: null },
  fsc: { type: 'application/vnd.fsc.weblaunch', charset: null },
  oas: { type: 'application/vnd.fujitsu.oasys', charset: null },
  oa2: { type: 'application/vnd.fujitsu.oasys2', charset: null },
  oa3: { type: 'application/vnd.fujitsu.oasys3', charset: null },
  fg5: { type: 'application/vnd.fujitsu.oasysgp', charset: null },
  bh2: { type: 'application/vnd.fujitsu.oasysprs', charset: null },
  ddd: { type: 'application/vnd.fujixerox.ddd', charset: null },
  xdw: { type: 'application/vnd.fujixerox.docuworks', charset: null },
  xbd: { type: 'application/vnd.fujixerox.docuworks.binder', charset: null },
  fzs: { type: 'application/vnd.fuzzysheet', charset: null },
  txd: { type: 'application/vnd.genomatix.tuxedo', charset: null },
  ggb: { type: 'application/vnd.geogebra.file', charset: null },
  ggs: { type: 'application/vnd.geogebra.slides', charset: null },
  ggt: { type: 'application/vnd.geogebra.tool', charset: null },
  gex: { type: 'application/vnd.geometry-explorer', charset: null },
  gre: null,
  gxt: { type: 'application/vnd.geonext', charset: null },
  g2w: { type: 'application/vnd.geoplan', charset: null },
  g3w: { type: 'application/vnd.geospace', charset: null },
  gmx: { type: 'application/vnd.gmx', charset: null },
  gdoc: { type: 'application/vnd.google-apps.document', charset: null },
  gdraw: { type: 'application/vnd.google-apps.drawing', charset: null },
  gform: { type: 'application/vnd.google-apps.form', charset: null },
  gjam: { type: 'application/vnd.google-apps.jam', charset: null },
  gmap: { type: 'application/vnd.google-apps.map', charset: null },
  gslides: { type: 'application/vnd.google-apps.presentation', charset: null },
  gscript: { type: 'application/vnd.google-apps.script', charset: null },
  gsite: { type: 'application/vnd.google-apps.site', charset: null },
  gsheet: { type: 'application/vnd.google-apps.spreadsheet', charset: null },
  kml: { type: 'application/vnd.google-earth.kml+xml', charset: null },
  kmz: { type: 'application/vnd.google-earth.kmz', charset: null },
  xdcf: { type: 'application/vnd.gov.sk.xmldatacontainer+xml', charset: null },
  gqf: { type: 'application/vnd.grafeq', charset: null },
  gqs: null,
  gac: { type: 'application/vnd.groove-account', charset: null },
  ghf: { type: 'application/vnd.groove-help', charset: null },
  gim: { type: 'application/vnd.groove-identity-message', charset: null },
  grv: { type: 'application/vnd.groove-injector', charset: null },
  gtm: { type: 'application/vnd.groove-tool-message', charset: null },
  tpl: { type: 'application/vnd.groove-tool-template', charset: null },
  vcg: { type: 'application/vnd.groove-vcard', charset: null },
  hal: { type: 'application/vnd.hal+xml', charset: null },
  zmm: { type: 'application/vnd.handheld-entertainment+xml', charset: null },
  hbci: { type: 'application/vnd.hbci', charset: null },
  les: { type: 'application/vnd.hhe.lesson-player', charset: null },
  hpgl: { type: 'application/vnd.hp-hpgl', charset: null },
  hpid: { type: 'application/vnd.hp-hpid', charset: null },
  hps: { type: 'application/vnd.hp-hps', charset: null },
  jlt: { type: 'application/vnd.hp-jlyt', charset: null },
  pcl: { type: 'application/vnd.hp-pcl', charset: null },
  pclxl: { type: 'application/vnd.hp-pclxl', charset: null },
  'sfd-hdstx': { type: 'application/vnd.hydrostatix.sof-data', charset: null },
  mpy: { type: 'application/vnd.ibm.minipay', charset: null },
  afp: { type: 'application/vnd.ibm.modcap', charset: null },
  listafp: null,
  list3820: null,
  irm: { type: 'application/vnd.ibm.rights-management', charset: null },
  sc: { type: 'application/vnd.ibm.secure-container', charset: null },
  icc: { type: 'application/vnd.iccprofile', charset: null },
  icm: null,
  igl: { type: 'application/vnd.igloader', charset: null },
  ivp: { type: 'application/vnd.immervision-ivp', charset: null },
  ivu: { type: 'application/vnd.immervision-ivu', charset: null },
  igm: { type: 'application/vnd.insors.igm', charset: null },
  xpw: { type: 'application/vnd.intercon.formnet', charset: null },
  xpx: null,
  i2g: { type: 'application/vnd.intergeo', charset: null },
  qbo: { type: 'application/vnd.intu.qbo', charset: null },
  qfx: { type: 'application/vnd.intu.qfx', charset: null },
  rcprofile: { type: 'application/vnd.ipunplugged.rcprofile', charset: null },
  irp: { type: 'application/vnd.irepository.package+xml', charset: null },
  xpr: { type: 'application/vnd.is-xpr', charset: null },
  fcs: { type: 'application/vnd.isac.fcs', charset: null },
  jam: { type: 'application/vnd.jam', charset: null },
  rms: { type: 'application/vnd.jcp.javame.midlet-rms', charset: null },
  jisp: { type: 'application/vnd.jisp', charset: null },
  joda: { type: 'application/vnd.joost.joda-archive', charset: null },
  ktz: { type: 'application/vnd.kahootz', charset: null },
  ktr: null,
  karbon: { type: 'application/vnd.kde.karbon', charset: null },
  chrt: { type: 'application/vnd.kde.kchart', charset: null },
  kfo: { type: 'application/vnd.kde.kformula', charset: null },
  flw: { type: 'application/vnd.kde.kivio', charset: null },
  kon: { type: 'application/vnd.kde.kontour', charset: null },
  kpr: { type: 'application/vnd.kde.kpresenter', charset: null },
  kpt: null,
  ksp: { type: 'application/vnd.kde.kspread', charset: null },
  kwd: { type: 'application/vnd.kde.kword', charset: null },
  kwt: null,
  htke: { type: 'application/vnd.kenameaapp', charset: null },
  kia: { type: 'application/vnd.kidspiration', charset: null },
  kne: { type: 'application/vnd.kinar', charset: null },
  knp: null,
  skp: { type: 'application/vnd.koan', charset: null },
  skd: null,
  skt: null,
  skm: null,
  sse: { type: 'application/vnd.kodak-descriptor', charset: null },
  lasxml: { type: 'application/vnd.las.las+xml', charset: null },
  lbd: { type: 'application/vnd.llamagraphics.life-balance.desktop', charset: null },
  lbe: { type: 'application/vnd.llamagraphics.life-balance.exchange+xml', charset: null },
  '123': { type: 'application/vnd.lotus-1-2-3', charset: null },
  apr: { type: 'application/vnd.lotus-approach', charset: null },
  pre: { type: 'application/vnd.lotus-freelance', charset: null },
  nsf: { type: 'application/vnd.lotus-notes', charset: null },
  org: { type: 'application/vnd.lotus-organizer', charset: null },
  scm: { type: 'application/vnd.lotus-screencam', charset: null },
  lwp: { type: 'application/vnd.lotus-wordpro', charset: null },
  portpkg: { type: 'application/vnd.macports.portpkg', charset: null },
  mvt: { type: 'application/vnd.mapbox-vector-tile', charset: null },
  mcd: { type: 'application/vnd.mcd', charset: null },
  mc1: { type: 'application/vnd.medcalcdata', charset: null },
  cdkey: { type: 'application/vnd.mediastation.cdkey', charset: null },
  mwf: { type: 'application/vnd.mfer', charset: null },
  mfm: { type: 'application/vnd.mfmp', charset: null },
  flo: { type: 'application/vnd.micrografx.flo', charset: null },
  igx: { type: 'application/vnd.micrografx.igx', charset: null },
  mif: { type: 'application/vnd.mif', charset: null },
  daf: { type: 'application/vnd.mobius.daf', charset: null },
  dis: { type: 'application/vnd.mobius.dis', charset: null },
  mbk: { type: 'application/vnd.mobius.mbk', charset: null },
  mqy: { type: 'application/vnd.mobius.mqy', charset: null },
  msl: { type: 'application/vnd.mobius.msl', charset: null },
  plc: { type: 'application/vnd.mobius.plc', charset: null },
  txf: { type: 'application/vnd.mobius.txf', charset: null },
  mpn: { type: 'application/vnd.mophun.application', charset: null },
  mpc: { type: 'application/vnd.mophun.certificate', charset: null },
  xul: { type: 'application/vnd.mozilla.xul+xml', charset: null },
  cil: { type: 'application/vnd.ms-artgalry', charset: null },
  cab: { type: 'application/vnd.ms-cab-compressed', charset: null },
  xls: { type: 'application/vnd.ms-excel', charset: null },
  xlm: null,
  xla: null,
  xlc: null,
  xlt: null,
  xlw: null,
  xlam: { type: 'application/vnd.ms-excel.addin.macroenabled.12', charset: null },
  xlsb: { type: 'application/vnd.ms-excel.sheet.binary.macroenabled.12', charset: null },
  xlsm: { type: 'application/vnd.ms-excel.sheet.macroenabled.12', charset: null },
  xltm: { type: 'application/vnd.ms-excel.template.macroenabled.12', charset: null },
  eot: { type: 'application/vnd.ms-fontobject', charset: null },
  chm: { type: 'application/vnd.ms-htmlhelp', charset: null },
  ims: { type: 'application/vnd.ms-ims', charset: null },
  lrm: { type: 'application/vnd.ms-lrm', charset: null },
  thmx: { type: 'application/vnd.ms-officetheme', charset: null },
  msg: { type: 'application/vnd.ms-outlook', charset: null },
  cat: { type: 'application/vnd.ms-pki.seccat', charset: null },
  stl: { type: 'application/vnd.ms-pki.stl', charset: null },
  ppt: { type: 'application/vnd.ms-powerpoint', charset: null },
  pps: null,
  pot: null,
  ppam: { type: 'application/vnd.ms-powerpoint.addin.macroenabled.12', charset: null },
  pptm: { type: 'application/vnd.ms-powerpoint.presentation.macroenabled.12', charset: null },
  sldm: { type: 'application/vnd.ms-powerpoint.slide.macroenabled.12', charset: null },
  ppsm: { type: 'application/vnd.ms-powerpoint.slideshow.macroenabled.12', charset: null },
  potm: { type: 'application/vnd.ms-powerpoint.template.macroenabled.12', charset: null },
  mpt: null,
  vdx: { type: 'application/vnd.ms-visio.viewer', charset: null },
  docm: { type: 'application/vnd.ms-word.document.macroenabled.12', charset: null },
  dotm: { type: 'application/vnd.ms-word.template.macroenabled.12', charset: null },
  wps: { type: 'application/vnd.ms-works', charset: null },
  wks: null,
  wcm: null,
  wdb: null,
  wpl: { type: 'application/vnd.ms-wpl', charset: null },
  xps: { type: 'application/vnd.ms-xpsdocument', charset: null },
  mseq: { type: 'application/vnd.mseq', charset: null },
  mus: { type: 'application/vnd.musician', charset: null },
  msty: { type: 'application/vnd.muvee.style', charset: null },
  taglet: { type: 'application/vnd.mynfc', charset: null },
  bdo: { type: 'application/vnd.nato.bindingdataobject+xml', charset: null },
  nlu: { type: 'application/vnd.neurolanguage.nlu', charset: null },
  ntf: { type: 'application/vnd.nitf', charset: null },
  nitf: null,
  nnd: { type: 'application/vnd.noblenet-directory', charset: null },
  nns: { type: 'application/vnd.noblenet-sealer', charset: null },
  nnw: { type: 'application/vnd.noblenet-web', charset: null },
  ngdat: { type: 'application/vnd.nokia.n-gage.data', charset: null },
  'n-gage': { type: 'application/vnd.nokia.n-gage.symbian.install', charset: null },
  rpst: { type: 'application/vnd.nokia.radio-preset', charset: null },
  rpss: { type: 'application/vnd.nokia.radio-presets', charset: null },
  edm: { type: 'application/vnd.novadigm.edm', charset: null },
  edx: { type: 'application/vnd.novadigm.edx', charset: null },
  ext: { type: 'application/vnd.novadigm.ext', charset: null },
  odc: { type: 'application/vnd.oasis.opendocument.chart', charset: null },
  otc: { type: 'application/vnd.oasis.opendocument.chart-template', charset: null },
  odb: { type: 'application/vnd.oasis.opendocument.database', charset: null },
  odf: { type: 'application/vnd.oasis.opendocument.formula', charset: null },
  odft: { type: 'application/vnd.oasis.opendocument.formula-template', charset: null },
  odg: { type: 'application/vnd.oasis.opendocument.graphics', charset: null },
  otg: { type: 'application/vnd.oasis.opendocument.graphics-template', charset: null },
  odi: { type: 'application/vnd.oasis.opendocument.image', charset: null },
  oti: { type: 'application/vnd.oasis.opendocument.image-template', charset: null },
  odp: { type: 'application/vnd.oasis.opendocument.presentation', charset: null },
  otp: { type: 'application/vnd.oasis.opendocument.presentation-template', charset: null },
  ods: { type: 'application/vnd.oasis.opendocument.spreadsheet', charset: null },
  ots: { type: 'application/vnd.oasis.opendocument.spreadsheet-template', charset: null },
  odt: { type: 'application/vnd.oasis.opendocument.text', charset: null },
  odm: { type: 'application/vnd.oasis.opendocument.text-master', charset: null },
  ott: { type: 'application/vnd.oasis.opendocument.text-template', charset: null },
  oth: { type: 'application/vnd.oasis.opendocument.text-web', charset: null },
  xo: { type: 'application/vnd.olpc-sugar', charset: null },
  dd2: { type: 'application/vnd.oma.dd2+xml', charset: null },
  obgx: { type: 'application/vnd.openblox.game+xml', charset: null },
  oxt: { type: 'application/vnd.openofficeorg.extension', charset: null },
  osm: { type: 'application/vnd.openstreetmap.data+xml', charset: null },
  pptx: { type: 'application/vnd.openxmlformats-officedocument.presentationml.presentation', charset: null },
  sldx: { type: 'application/vnd.openxmlformats-officedocument.presentationml.slide', charset: null },
  ppsx: { type: 'application/vnd.openxmlformats-officedocument.presentationml.slideshow', charset: null },
  potx: { type: 'application/vnd.openxmlformats-officedocument.presentationml.template', charset: null },
  xlsx: { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', charset: null },
  xltx: { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.template', charset: null },
  docx: { type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', charset: null },
  dotx: { type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.template', charset: null },
  mgp: { type: 'application/vnd.osgeo.mapguide.package', charset: null },
  dp: { type: 'application/vnd.osgi.dp', charset: null },
  esa: { type: 'application/vnd.osgi.subsystem', charset: null },
  pdb: { type: 'application/vnd.palm', charset: null },
  pqa: null,
  oprc: null,
  paw: { type: 'application/vnd.pawaafile', charset: null },
  str: { type: 'application/vnd.pg.format', charset: null },
  ei6: { type: 'application/vnd.pg.osasli', charset: null },
  efif: { type: 'application/vnd.picsel', charset: null },
  wg: { type: 'application/vnd.pmi.widget', charset: null },
  plf: { type: 'application/vnd.pocketlearn', charset: null },
  pbd: { type: 'application/vnd.powerbuilder6', charset: null },
  box: { type: 'application/vnd.previewsystems.box', charset: null },
  brushset: { type: 'application/vnd.procrate.brushset', charset: null },
  brush: { type: 'application/vnd.procreate.brush', charset: null },
  drm: { type: 'application/vnd.procreate.dream', charset: null },
  mgz: { type: 'application/vnd.proteus.magazine', charset: null },
  qps: { type: 'application/vnd.publishare-delta-tree', charset: null },
  ptid: { type: 'application/vnd.pvi.ptid1', charset: null },
  xhtm: { type: 'application/vnd.pwg-xhtml-print+xml', charset: null },
  qxd: { type: 'application/vnd.quark.quarkxpress', charset: null },
  qxt: null,
  qwd: null,
  qwt: null,
  qxl: null,
  qxb: null,
  rar: { type: 'application/vnd.rar', charset: null },
  bed: { type: 'application/vnd.realvnc.bed', charset: null },
  mxl: { type: 'application/vnd.recordare.musicxml', charset: null },
  musicxml: { type: 'application/vnd.recordare.musicxml+xml', charset: null },
  cryptonote: { type: 'application/vnd.rig.cryptonote', charset: null },
  cod: { type: 'application/vnd.rim.cod', charset: null },
  rm: { type: 'application/vnd.rn-realmedia', charset: null },
  rmvb: { type: 'application/vnd.rn-realmedia-vbr', charset: null },
  link66: { type: 'application/vnd.route66.link66+xml', charset: null },
  st: { type: 'application/vnd.sailingtracker.track', charset: null },
  see: { type: 'application/vnd.seemail', charset: null },
  sema: { type: 'application/vnd.sema', charset: null },
  semd: { type: 'application/vnd.semd', charset: null },
  semf: { type: 'application/vnd.semf', charset: null },
  ifm: { type: 'application/vnd.shana.informed.formdata', charset: null },
  itp: { type: 'application/vnd.shana.informed.formtemplate', charset: null },
  iif: { type: 'application/vnd.shana.informed.interchange', charset: null },
  ipk: { type: 'application/vnd.shana.informed.package', charset: null },
  twd: { type: 'application/vnd.simtech-mindmapper', charset: null },
  twds: null,
  mmf: { type: 'application/vnd.smaf', charset: null },
  teacher: { type: 'application/vnd.smart.teacher', charset: null },
  fo: { type: 'application/vnd.software602.filler.form+xml', charset: null },
  sdkm: { type: 'application/vnd.solent.sdkm+xml', charset: null },
  sdkd: null,
  dxp: { type: 'application/vnd.spotfire.dxp', charset: null },
  sfs: { type: 'application/vnd.spotfire.sfs', charset: null },
  sdc: { type: 'application/vnd.stardivision.calc', charset: null },
  sda: { type: 'application/vnd.stardivision.draw', charset: null },
  sdd: { type: 'application/vnd.stardivision.impress', charset: null },
  smf: { type: 'application/vnd.stardivision.math', charset: null },
  sdw: { type: 'application/vnd.stardivision.writer', charset: null },
  vor: null,
  sgl: { type: 'application/vnd.stardivision.writer-global', charset: null },
  smzip: { type: 'application/vnd.stepmania.package', charset: null },
  sm: { type: 'application/vnd.stepmania.stepchart', charset: null },
  wadl: { type: 'application/vnd.sun.wadl+xml', charset: null },
  sxc: { type: 'application/vnd.sun.xml.calc', charset: null },
  stc: { type: 'application/vnd.sun.xml.calc.template', charset: null },
  sxd: { type: 'application/vnd.sun.xml.draw', charset: null },
  std: { type: 'application/vnd.sun.xml.draw.template', charset: null },
  sxi: { type: 'application/vnd.sun.xml.impress', charset: null },
  sti: { type: 'application/vnd.sun.xml.impress.template', charset: null },
  sxm: { type: 'application/vnd.sun.xml.math', charset: null },
  sxw: { type: 'application/vnd.sun.xml.writer', charset: null },
  sxg: { type: 'application/vnd.sun.xml.writer.global', charset: null },
  stw: { type: 'application/vnd.sun.xml.writer.template', charset: null },
  sus: { type: 'application/vnd.sus-calendar', charset: null },
  susp: null,
  svd: { type: 'application/vnd.svd', charset: null },
  sis: { type: 'application/vnd.symbian.install', charset: null },
  sisx: null,
  xsm: { type: 'application/vnd.syncml+xml', charset: 'utf-8' },
  bdm: { type: 'application/vnd.syncml.dm+wbxml', charset: 'utf-8' },
  xdm: { type: 'application/vnd.syncml.dm+xml', charset: 'utf-8' },
  ddf: { type: 'application/vnd.syncml.dmddf+xml', charset: 'utf-8' },
  tao: { type: 'application/vnd.tao.intent-module-archive', charset: null },
  pcap: { type: 'application/vnd.tcpdump.pcap', charset: null },
  cap: null,
  dmp: null,
  tmo: { type: 'application/vnd.tmobile-livetv', charset: null },
  tpt: { type: 'application/vnd.trid.tpt', charset: null },
  mxs: { type: 'application/vnd.triscape.mxs', charset: null },
  tra: { type: 'application/vnd.trueapp', charset: null },
  ufd: { type: 'application/vnd.ufdl', charset: null },
  ufdl: null,
  utz: { type: 'application/vnd.uiq.theme', charset: null },
  umj: { type: 'application/vnd.umajin', charset: null },
  unityweb: { type: 'application/vnd.unity', charset: null },
  uoml: { type: 'application/vnd.uoml+xml', charset: null },
  uo: null,
  vcx: { type: 'application/vnd.vcx', charset: null },
  vsd: { type: 'application/vnd.visio', charset: null },
  vst: null,
  vss: null,
  vsw: null,
  vsdx: null,
  vtx: null,
  vis: { type: 'application/vnd.visionary', charset: null },
  vsf: { type: 'application/vnd.vsf', charset: null },
  wbxml: { type: 'application/vnd.wap.wbxml', charset: 'utf-8' },
  wmlc: { type: 'application/vnd.wap.wmlc', charset: null },
  wmlsc: { type: 'application/vnd.wap.wmlscriptc', charset: null },
  wtb: { type: 'application/vnd.webturbo', charset: null },
  nbp: { type: 'application/vnd.wolfram.player', charset: null },
  wpd: { type: 'application/vnd.wordperfect', charset: null },
  wqd: { type: 'application/vnd.wqd', charset: null },
  stf: { type: 'application/vnd.wt.stf', charset: null },
  xar: { type: 'application/vnd.xara', charset: null },
  xfdl: { type: 'application/vnd.xfdl', charset: null },
  hvd: { type: 'application/vnd.yamaha.hv-dic', charset: null },
  hvs: { type: 'application/vnd.yamaha.hv-script', charset: null },
  hvp: { type: 'application/vnd.yamaha.hv-voice', charset: null },
  osf: { type: 'application/vnd.yamaha.openscoreformat', charset: null },
  osfpvg: { type: 'application/vnd.yamaha.openscoreformat.osfpvg+xml', charset: null },
  saf: { type: 'application/vnd.yamaha.smaf-audio', charset: null },
  spf: { type: 'application/vnd.yamaha.smaf-phrase', charset: null },
  cmp: { type: 'application/vnd.yellowriver-custom-menu', charset: null },
  zir: { type: 'application/vnd.zul', charset: null },
  zirz: null,
  zaz: { type: 'application/vnd.zzazz.deck+xml', charset: null },
  vxml: { type: 'application/voicexml+xml', charset: null },
  wasm: { type: 'application/wasm', charset: null },
  wif: { type: 'application/watcherinfo+xml', charset: null },
  wgt: { type: 'application/widget', charset: null },
  hlp: { type: 'application/winhlp', charset: null },
  wsdl: { type: 'application/wsdl+xml', charset: null },
  wspolicy: { type: 'application/wspolicy+xml', charset: null },
  '7z': { type: 'application/x-7z-compressed', charset: null },
  abw: { type: 'application/x-abiword', charset: null },
  ace: { type: 'application/x-ace-compressed', charset: null },
  arj: { type: 'application/x-arj', charset: null },
  aab: { type: 'application/x-authorware-bin', charset: null },
  x32: null,
  u32: null,
  vox: null,
  aam: { type: 'application/x-authorware-map', charset: null },
  aas: { type: 'application/x-authorware-seg', charset: null },
  bcpio: { type: 'application/x-bcpio', charset: null },
  torrent: { type: 'application/x-bittorrent', charset: null },
  blend: { type: 'application/x-blender', charset: null },
  blb: { type: 'application/x-blorb', charset: null },
  blorb: null,
  bz: { type: 'application/x-bzip', charset: null },
  bz2: { type: 'application/x-bzip2', charset: null },
  boz: null,
  cbr: { type: 'application/x-cbr', charset: null },
  cba: null,
  cbt: null,
  cbz: null,
  cb7: null,
  vcd: { type: 'application/x-cdlink', charset: null },
  cfs: { type: 'application/x-cfs-compressed', charset: null },
  chat: { type: 'application/x-chat', charset: null },
  pgn: { type: 'application/x-chess-pgn', charset: null },
  crx: { type: 'application/x-chrome-extension', charset: null },
  cco: { type: 'application/x-cocoa', charset: null },
  nsc: { type: 'application/x-conference', charset: null },
  cpio: { type: 'application/x-cpio', charset: null },
  csh: { type: 'application/x-csh', charset: null },
  udeb: null,
  dgc: { type: 'application/x-dgc-compressed', charset: null },
  dir: { type: 'application/x-director', charset: null },
  dcr: null,
  dxr: null,
  cst: null,
  cct: null,
  cxt: null,
  w3d: null,
  fgd: null,
  swa: null,
  wad: { type: 'application/x-doom', charset: null },
  ncx: { type: 'application/x-dtbncx+xml', charset: null },
  dtb: { type: 'application/x-dtbook+xml', charset: null },
  res: { type: 'application/x-dtbresource+xml', charset: null },
  dvi: { type: 'application/x-dvi', charset: null },
  evy: { type: 'application/x-envoy', charset: null },
  eva: { type: 'application/x-eva', charset: null },
  bdf: { type: 'application/x-font-bdf', charset: null },
  gsf: { type: 'application/x-font-ghostscript', charset: null },
  psf: { type: 'application/x-font-linux-psf', charset: null },
  pcf: { type: 'application/x-font-pcf', charset: null },
  snf: { type: 'application/x-font-snf', charset: null },
  pfa: { type: 'application/x-font-type1', charset: null },
  pfb: null,
  pfm: null,
  afm: null,
  arc: { type: 'application/x-freearc', charset: null },
  spl: { type: 'application/x-futuresplash', charset: null },
  gca: { type: 'application/x-gca-compressed', charset: null },
  ulx: { type: 'application/x-glulx', charset: null },
  gnumeric: { type: 'application/x-gnumeric', charset: null },
  gramps: { type: 'application/x-gramps-xml', charset: null },
  gtar: { type: 'application/x-gtar', charset: null },
  hdf: { type: 'application/x-hdf', charset: null },
  php: { type: 'application/x-httpd-php', charset: null },
  install: { type: 'application/x-install-instructions', charset: null },
  ipynb: { type: 'application/x-ipynb+json', charset: null },
  jardiff: { type: 'application/x-java-archive-diff', charset: null },
  jnlp: { type: 'application/x-java-jnlp-file', charset: null },
  kdbx: { type: 'application/x-keepass2', charset: null },
  latex: { type: 'application/x-latex', charset: null },
  luac: { type: 'application/x-lua-bytecode', charset: null },
  lzh: { type: 'application/x-lzh-compressed', charset: null },
  lha: null,
  run: { type: 'application/x-makeself', charset: null },
  mie: { type: 'application/x-mie', charset: null },
  prc: { type: 'application/x-mobipocket-ebook', charset: null },
  mobi: null,
  application: { type: 'application/x-ms-application', charset: null },
  lnk: { type: 'application/x-ms-shortcut', charset: null },
  wmd: { type: 'application/x-ms-wmd', charset: null },
  wmz: { type: 'application/x-ms-wmz', charset: null },
  xbap: { type: 'application/x-ms-xbap', charset: null },
  mdb: { type: 'application/x-msaccess', charset: null },
  obd: { type: 'application/x-msbinder', charset: null },
  crd: { type: 'application/x-mscardfile', charset: null },
  clp: { type: 'application/x-msclip', charset: null },
  com: null,
  bat: null,
  mvb: { type: 'application/x-msmediaview', charset: null },
  m13: null,
  m14: null,
  wmf: { type: 'application/x-msmetafile', charset: null },
  emf: null,
  emz: null,
  mny: { type: 'application/x-msmoney', charset: null },
  pub: { type: 'application/x-mspublisher', charset: null },
  scd: { type: 'application/x-msschedule', charset: null },
  trm: { type: 'application/x-msterminal', charset: null },
  wri: { type: 'application/x-mswrite', charset: null },
  nc: { type: 'application/x-netcdf', charset: null },
  cdf: null,
  pac: { type: 'application/x-ns-proxy-autoconfig', charset: null },
  nzb: { type: 'application/x-nzb', charset: null },
  pl: { type: 'application/x-perl', charset: null },
  pm: null,
  p12: { type: 'application/x-pkcs12', charset: null },
  pfx: null,
  p7b: { type: 'application/x-pkcs7-certificates', charset: null },
  spc: null,
  p7r: { type: 'application/x-pkcs7-certreqresp', charset: null },
  rpm: { type: 'application/x-redhat-package-manager', charset: null },
  ris: { type: 'application/x-research-info-systems', charset: null },
  sea: { type: 'application/x-sea', charset: null },
  sh: { type: 'application/x-sh', charset: null },
  shar: { type: 'application/x-shar', charset: null },
  swf: { type: 'application/x-shockwave-flash', charset: null },
  xap: { type: 'application/x-silverlight-app', charset: null },
  sit: { type: 'application/x-stuffit', charset: null },
  sitx: { type: 'application/x-stuffitx', charset: null },
  srt: { type: 'application/x-subrip', charset: null },
  sv4cpio: { type: 'application/x-sv4cpio', charset: null },
  sv4crc: { type: 'application/x-sv4crc', charset: null },
  t3: { type: 'application/x-t3vm-image', charset: null },
  gam: { type: 'application/x-tads', charset: null },
  tar: { type: 'application/x-tar', charset: null },
  tcl: { type: 'application/x-tcl', charset: null },
  tk: null,
  tex: { type: 'application/x-tex', charset: null },
  tfm: { type: 'application/x-tex-tfm', charset: null },
  texinfo: { type: 'application/x-texinfo', charset: null },
  texi: null,
  obj: { type: 'application/x-tgif', charset: null },
  ustar: { type: 'application/x-ustar', charset: null },
  hdd: { type: 'application/x-virtualbox-hdd', charset: null },
  ova: { type: 'application/x-virtualbox-ova', charset: null },
  ovf: { type: 'application/x-virtualbox-ovf', charset: null },
  vbox: { type: 'application/x-virtualbox-vbox', charset: null },
  'vbox-extpack': { type: 'application/x-virtualbox-vbox-extpack', charset: null },
  vdi: { type: 'application/x-virtualbox-vdi', charset: null },
  vhd: { type: 'application/x-virtualbox-vhd', charset: null },
  vmdk: { type: 'application/x-virtualbox-vmdk', charset: null },
  src: { type: 'application/x-wais-source', charset: null },
  webapp: { type: 'application/x-web-app-manifest+json', charset: null },
  der: { type: 'application/x-x509-ca-cert', charset: null },
  crt: null,
  pem: null,
  fig: { type: 'application/x-xfig', charset: null },
  xlf: { type: 'application/x-xliff+xml', charset: null },
  xpi: { type: 'application/x-xpinstall', charset: null },
  xz: { type: 'application/x-xz', charset: null },
  zip: { type: 'application/x-zip-compressed', charset: null },
  z1: { type: 'application/x-zmachine', charset: null },
  z2: null,
  z3: null,
  z4: null,
  z5: null,
  z6: null,
  z7: null,
  z8: null,
  xaml: { type: 'application/xaml+xml', charset: null },
  xav: { type: 'application/xcap-att+xml', charset: null },
  xca: { type: 'application/xcap-caps+xml', charset: null },
  xdf: { type: 'application/xcap-diff+xml', charset: null },
  xel: { type: 'application/xcap-el+xml', charset: null },
  xns: { type: 'application/xcap-ns+xml', charset: null },
  xenc: { type: 'application/xenc+xml', charset: null },
  xhtml: { type: 'application/xhtml+xml', charset: null },
  xht: null,
  xml: { type: 'application/xml', charset: null },
  xsl: null,
  xsd: null,
  rng: null,
  dtd: { type: 'application/xml-dtd', charset: null },
  xop: { type: 'application/xop+xml', charset: null },
  xpl: { type: 'application/xproc+xml', charset: null },
  xslt: null,
  xspf: { type: 'application/xspf+xml', charset: null },
  mxml: { type: 'application/xv+xml', charset: null },
  xhvml: null,
  xvml: null,
  xvm: null,
  yang: { type: 'application/yang', charset: null },
  yin: { type: 'application/yin+xml', charset: null },
  lottie: { type: 'application/zip+dotlottie', charset: null },
  '3gpp': { type: 'audio/3gpp', charset: null },
  adts: { type: 'audio/aac', charset: null },
  aac: null,
  adp: { type: 'audio/adpcm', charset: null },
  amr: { type: 'audio/amr', charset: null },
  au: { type: 'audio/basic', charset: null },
  snd: null,
  mid: { type: 'audio/midi', charset: null },
  midi: null,
  kar: null,
  rmi: null,
  mxmf: { type: 'audio/mobile-xmf', charset: null },
  mp3: { type: 'audio/mp3', charset: null },
  m4a: { type: 'audio/mp4', charset: null },
  mp4a: null,
  m4b: null,
  mpga: { type: 'audio/mpeg', charset: null },
  mp2: null,
  mp2a: null,
  m2a: null,
  m3a: null,
  oga: { type: 'audio/ogg', charset: null },
  ogg: null,
  spx: null,
  opus: null,
  s3m: { type: 'audio/s3m', charset: null },
  sil: { type: 'audio/silk', charset: null },
  uva: { type: 'audio/vnd.dece.audio', charset: null },
  uvva: null,
  eol: { type: 'audio/vnd.digital-winds', charset: null },
  dra: { type: 'audio/vnd.dra', charset: null },
  dts: { type: 'audio/vnd.dts', charset: null },
  dtshd: { type: 'audio/vnd.dts.hd', charset: null },
  lvp: { type: 'audio/vnd.lucent.voice', charset: null },
  pya: { type: 'audio/vnd.ms-playready.media.pya', charset: null },
  ecelp4800: { type: 'audio/vnd.nuera.ecelp4800', charset: null },
  ecelp7470: { type: 'audio/vnd.nuera.ecelp7470', charset: null },
  ecelp9600: { type: 'audio/vnd.nuera.ecelp9600', charset: null },
  rip: { type: 'audio/vnd.rip', charset: null },
  wav: { type: 'audio/wav', charset: null },
  weba: { type: 'audio/webm', charset: null },
  aif: { type: 'audio/x-aiff', charset: null },
  aiff: null,
  aifc: null,
  caf: { type: 'audio/x-caf', charset: null },
  flac: { type: 'audio/x-flac', charset: null },
  mka: { type: 'audio/x-matroska', charset: null },
  m3u: { type: 'audio/x-mpegurl', charset: null },
  wax: { type: 'audio/x-ms-wax', charset: null },
  wma: { type: 'audio/x-ms-wma', charset: null },
  ram: { type: 'audio/x-pn-realaudio', charset: null },
  ra: null,
  rmp: { type: 'audio/x-pn-realaudio-plugin', charset: null },
  xm: { type: 'audio/xm', charset: null },
  cdx: { type: 'chemical/x-cdx', charset: null },
  cif: { type: 'chemical/x-cif', charset: null },
  cmdf: { type: 'chemical/x-cmdf', charset: null },
  cml: { type: 'chemical/x-cml', charset: null },
  csml: { type: 'chemical/x-csml', charset: null },
  xyz: { type: 'chemical/x-xyz', charset: null },
  ttc: { type: 'font/collection', charset: null },
  otf: { type: 'font/otf', charset: null },
  ttf: { type: 'font/ttf', charset: null },
  woff: { type: 'font/woff', charset: null },
  woff2: { type: 'font/woff2', charset: null },
  exr: { type: 'image/aces', charset: null },
  apng: { type: 'image/apng', charset: null },
  avci: { type: 'image/avci', charset: null },
  avcs: { type: 'image/avcs', charset: null },
  avif: { type: 'image/avif', charset: null },
  bmp: { type: 'image/bmp', charset: null },
  dib: null,
  cgm: { type: 'image/cgm', charset: null },
  drle: { type: 'image/dicom-rle', charset: null },
  dpx: { type: 'image/dpx', charset: null },
  fits: { type: 'image/fits', charset: null },
  g3: { type: 'image/g3fax', charset: null },
  gif: { type: 'image/gif', charset: null },
  heic: { type: 'image/heic', charset: null },
  heics: { type: 'image/heic-sequence', charset: null },
  heif: { type: 'image/heif', charset: null },
  heifs: { type: 'image/heif-sequence', charset: null },
  hej2: { type: 'image/hej2k', charset: null },
  ief: { type: 'image/ief', charset: null },
  jaii: { type: 'image/jaii', charset: null },
  jais: { type: 'image/jais', charset: null },
  jls: { type: 'image/jls', charset: null },
  jp2: { type: 'image/jp2', charset: null },
  jpg2: null,
  jpg: { type: 'image/jpeg', charset: null },
  jpeg: null,
  jpe: null,
  jph: { type: 'image/jph', charset: null },
  jhc: { type: 'image/jphc', charset: null },
  jpm: { type: 'image/jpm', charset: null },
  jpgm: null,
  jpx: { type: 'image/jpx', charset: null },
  jpf: null,
  jxl: { type: 'image/jxl', charset: null },
  jxr: { type: 'image/jxr', charset: null },
  jxra: { type: 'image/jxra', charset: null },
  jxrs: { type: 'image/jxrs', charset: null },
  jxs: { type: 'image/jxs', charset: null },
  jxsc: { type: 'image/jxsc', charset: null },
  jxsi: { type: 'image/jxsi', charset: null },
  jxss: { type: 'image/jxss', charset: null },
  ktx: { type: 'image/ktx', charset: null },
  ktx2: { type: 'image/ktx2', charset: null },
  jfif: { type: 'image/pjpeg', charset: null },
  png: { type: 'image/png', charset: null },
  btif: { type: 'image/prs.btif', charset: null },
  btf: null,
  pti: { type: 'image/prs.pti', charset: null },
  sgi: { type: 'image/sgi', charset: null },
  svg: { type: 'image/svg+xml', charset: null },
  svgz: null,
  t38: { type: 'image/t38', charset: null },
  tif: { type: 'image/tiff', charset: null },
  tiff: null,
  tfx: { type: 'image/tiff-fx', charset: null },
  psd: { type: 'image/vnd.adobe.photoshop', charset: null },
  azv: { type: 'image/vnd.airzip.accelerator.azv', charset: null },
  uvi: { type: 'image/vnd.dece.graphic', charset: null },
  uvvi: null,
  uvg: null,
  uvvg: null,
  djvu: { type: 'image/vnd.djvu', charset: null },
  djv: null,
  sub: { type: 'image/vnd.dvb.subtitle', charset: null },
  dwg: { type: 'image/vnd.dwg', charset: null },
  dxf: { type: 'image/vnd.dxf', charset: null },
  fbs: { type: 'image/vnd.fastbidsheet', charset: null },
  fpx: { type: 'image/vnd.fpx', charset: null },
  fst: { type: 'image/vnd.fst', charset: null },
  mmr: { type: 'image/vnd.fujixerox.edmics-mmr', charset: null },
  rlc: { type: 'image/vnd.fujixerox.edmics-rlc', charset: null },
  ico: { type: 'image/vnd.microsoft.icon', charset: null },
  dds: { type: 'image/vnd.ms-dds', charset: null },
  mdi: { type: 'image/vnd.ms-modi', charset: null },
  wdp: { type: 'image/vnd.ms-photo', charset: null },
  npx: { type: 'image/vnd.net-fpx', charset: null },
  b16: { type: 'image/vnd.pco.b16', charset: null },
  tap: { type: 'image/vnd.tencent.tap', charset: null },
  vtf: { type: 'image/vnd.valve.source.texture', charset: null },
  wbmp: { type: 'image/vnd.wap.wbmp', charset: null },
  xif: { type: 'image/vnd.xiff', charset: null },
  pcx: { type: 'image/vnd.zbrush.pcx', charset: null },
  webp: { type: 'image/webp', charset: null },
  '3ds': { type: 'image/x-3ds', charset: null },
  dng: { type: 'image/x-adobe-dng', charset: null },
  ras: { type: 'image/x-cmu-raster', charset: null },
  cmx: { type: 'image/x-cmx', charset: null },
  fh: { type: 'image/x-freehand', charset: null },
  fhc: null,
  fh4: null,
  fh5: null,
  fh7: null,
  jng: { type: 'image/x-jng', charset: null },
  sid: { type: 'image/x-mrsid-image', charset: null },
  pic: { type: 'image/x-pict', charset: null },
  pct: null,
  pnm: { type: 'image/x-portable-anymap', charset: null },
  pbm: { type: 'image/x-portable-bitmap', charset: null },
  pgm: { type: 'image/x-portable-graymap', charset: null },
  ppm: { type: 'image/x-portable-pixmap', charset: null },
  rgb: { type: 'image/x-rgb', charset: null },
  tga: { type: 'image/x-tga', charset: null },
  xbm: { type: 'image/x-xbitmap', charset: null },
  xpm: { type: 'image/x-xpixmap', charset: null },
  xwd: { type: 'image/x-xwindowdump', charset: null },
  'disposition-notification': { type: 'message/disposition-notification', charset: null },
  u8msg: { type: 'message/global', charset: null },
  u8dsn: { type: 'message/global-delivery-status', charset: null },
  u8mdn: { type: 'message/global-disposition-notification', charset: null },
  u8hdr: { type: 'message/global-headers', charset: null },
  eml: { type: 'message/rfc822', charset: null },
  mime: null,
  mht: null,
  mhtml: null,
  wsc: { type: 'message/vnd.wfa.wsc', charset: null },
  '3mf': { type: 'model/3mf', charset: null },
  gltf: { type: 'model/gltf+json', charset: null },
  glb: { type: 'model/gltf-binary', charset: null },
  igs: { type: 'model/iges', charset: null },
  iges: null,
  jt: { type: 'model/jt', charset: null },
  msh: { type: 'model/mesh', charset: null },
  mesh: null,
  silo: null,
  mtl: { type: 'model/mtl', charset: null },
  step: { type: 'model/step', charset: null },
  stp: null,
  stpnc: null,
  p21: null,
  '210': null,
  stpx: { type: 'model/step+xml', charset: null },
  stpz: { type: 'model/step+zip', charset: null },
  stpxz: { type: 'model/step-xml+zip', charset: null },
  u3d: { type: 'model/u3d', charset: null },
  bary: { type: 'model/vnd.bary', charset: null },
  cld: { type: 'model/vnd.cld', charset: null },
  dae: { type: 'model/vnd.collada+xml', charset: null },
  dwf: { type: 'model/vnd.dwf', charset: null },
  gdl: { type: 'model/vnd.gdl', charset: null },
  gtw: { type: 'model/vnd.gtw', charset: null },
  mts: { type: 'model/vnd.mts', charset: null },
  ogex: { type: 'model/vnd.opengex', charset: null },
  x_b: { type: 'model/vnd.parasolid.transmit.binary', charset: null },
  x_t: { type: 'model/vnd.parasolid.transmit.text', charset: null },
  pyo: { type: 'model/vnd.pytha.pyox', charset: null },
  pyox: null,
  vds: { type: 'model/vnd.sap.vds', charset: null },
  usda: { type: 'model/vnd.usda', charset: null },
  usdz: { type: 'model/vnd.usdz+zip', charset: null },
  bsp: { type: 'model/vnd.valve.source.compiled-map', charset: null },
  vtu: { type: 'model/vnd.vtu', charset: null },
  wrl: { type: 'model/vrml', charset: null },
  vrml: null,
  x3db: { type: 'model/x3d+binary', charset: null },
  x3dbz: null,
  x3dv: { type: 'model/x3d+vrml', charset: null },
  x3dvz: null,
  x3d: { type: 'model/x3d+xml', charset: null },
  x3dz: null,
  appcache: { type: 'text/cache-manifest', charset: null },
  manifest: null,
  ics: { type: 'text/calendar', charset: null },
  ifb: null,
  coffee: { type: 'text/coffeescript', charset: null },
  litcoffee: null,
  css: { type: 'text/css', charset: 'utf-8' },
  csv: { type: 'text/csv', charset: null },
  html: { type: 'text/html', charset: null },
  htm: null,
  shtml: null,
  jade: { type: 'text/jade', charset: null },
  mjs: null,
  jsx: { type: 'text/jsx', charset: null },
  less: { type: 'text/less', charset: null },
  md: { type: 'text/markdown', charset: null },
  markdown: null,
  mml: { type: 'text/mathml', charset: null },
  mdx: { type: 'text/mdx', charset: null },
  n3: { type: 'text/n3', charset: 'utf-8' },
  txt: { type: 'text/plain', charset: null },
  text: null,
  conf: null,
  def: null,
  list: null,
  log: null,
  in: null,
  ini: null,
  dsc: { type: 'text/prs.lines.tag', charset: null },
  rtx: { type: 'text/richtext', charset: null },
  sgml: { type: 'text/sgml', charset: null },
  sgm: null,
  shex: { type: 'text/shex', charset: null },
  slim: { type: 'text/slim', charset: null },
  slm: null,
  spdx: { type: 'text/spdx', charset: null },
  stylus: { type: 'text/stylus', charset: null },
  styl: null,
  tsv: { type: 'text/tab-separated-values', charset: null },
  t: { type: 'text/troff', charset: null },
  tr: null,
  roff: null,
  man: null,
  me: null,
  ms: null,
  ttl: { type: 'text/turtle', charset: 'utf-8' },
  uri: { type: 'text/uri-list', charset: null },
  uris: null,
  urls: null,
  vcard: { type: 'text/vcard', charset: null },
  curl: { type: 'text/vnd.curl', charset: null },
  dcurl: { type: 'text/vnd.curl.dcurl', charset: null },
  mcurl: { type: 'text/vnd.curl.mcurl', charset: null },
  scurl: { type: 'text/vnd.curl.scurl', charset: null },
  ged: { type: 'text/vnd.familysearch.gedcom', charset: null },
  fly: { type: 'text/vnd.fly', charset: null },
  flx: { type: 'text/vnd.fmi.flexstor', charset: null },
  gv: { type: 'text/vnd.graphviz', charset: null },
  '3dml': { type: 'text/vnd.in3d.3dml', charset: null },
  spot: { type: 'text/vnd.in3d.spot', charset: null },
  jad: { type: 'text/vnd.sun.j2me.app-descriptor', charset: 'utf-8' },
  wml: { type: 'text/vnd.wap.wml', charset: null },
  wmls: { type: 'text/vnd.wap.wmlscript', charset: null },
  vtt: { type: 'text/vtt', charset: 'utf-8' },
  wgsl: { type: 'text/wgsl', charset: null },
  s: { type: 'text/x-asm', charset: null },
  asm: null,
  c: { type: 'text/x-c', charset: null },
  cc: null,
  cxx: null,
  cpp: null,
  h: null,
  hh: null,
  dic: null,
  htc: { type: 'text/x-component', charset: null },
  f: { type: 'text/x-fortran', charset: null },
  for: null,
  f77: null,
  f90: null,
  hbs: { type: 'text/x-handlebars-template', charset: null },
  java: { type: 'text/x-java-source', charset: null },
  lua: { type: 'text/x-lua', charset: null },
  mkd: { type: 'text/x-markdown', charset: null },
  nfo: { type: 'text/x-nfo', charset: null },
  opml: { type: 'text/x-opml', charset: null },
  p: { type: 'text/x-pascal', charset: null },
  pas: null,
  pde: { type: 'text/x-processing', charset: null },
  sass: { type: 'text/x-sass', charset: null },
  scss: { type: 'text/x-scss', charset: null },
  etx: { type: 'text/x-setext', charset: null },
  sfv: { type: 'text/x-sfv', charset: null },
  ymp: { type: 'text/x-suse-ymp', charset: null },
  uu: { type: 'text/x-uuencode', charset: null },
  vcs: { type: 'text/x-vcalendar', charset: null },
  vcf: { type: 'text/x-vcard', charset: null },
  yaml: { type: 'text/yaml', charset: null },
  yml: null,
  '3gp': { type: 'video/3gpp', charset: null },
  '3g2': { type: 'video/3gpp2', charset: null },
  h261: { type: 'video/h261', charset: null },
  h263: { type: 'video/h263', charset: null },
  h264: { type: 'video/h264', charset: null },
  m4s: { type: 'video/iso.segment', charset: null },
  jpgv: { type: 'video/jpeg', charset: null },
  mj2: { type: 'video/mj2', charset: null },
  mjp2: null,
  ts: { type: 'video/mp2t', charset: null },
  m2t: null,
  m2ts: null,
  mp4v: null,
  mpeg: { type: 'video/mpeg', charset: null },
  mpg: null,
  mpe: null,
  m1v: null,
  m2v: null,
  ogv: { type: 'video/ogg', charset: null },
  qt: { type: 'video/quicktime', charset: null },
  mov: null,
  uvh: { type: 'video/vnd.dece.hd', charset: null },
  uvvh: null,
  uvm: { type: 'video/vnd.dece.mobile', charset: null },
  uvvm: null,
  uvp: { type: 'video/vnd.dece.pd', charset: null },
  uvvp: null,
  uvs: { type: 'video/vnd.dece.sd', charset: null },
  uvvs: null,
  uvv: { type: 'video/vnd.dece.video', charset: null },
  uvvv: null,
  dvb: { type: 'video/vnd.dvb.file', charset: null },
  fvt: { type: 'video/vnd.fvt', charset: null },
  mxu: { type: 'video/vnd.mpegurl', charset: null },
  m4u: null,
  pyv: { type: 'video/vnd.ms-playready.media.pyv', charset: null },
  uvu: { type: 'video/vnd.uvvu.mp4', charset: null },
  uvvu: null,
  viv: { type: 'video/vnd.vivo', charset: null },
  webm: { type: 'video/webm', charset: null },
  f4v: { type: 'video/x-f4v', charset: null },
  fli: { type: 'video/x-fli', charset: null },
  flv: { type: 'video/x-flv', charset: null },
  m4v: { type: 'video/x-m4v', charset: null },
  mkv: { type: 'video/x-matroska', charset: null },
  mk3d: null,
  mks: null,
  mng: { type: 'video/x-mng', charset: null },
  asf: { type: 'video/x-ms-asf', charset: null },
  asx: null,
  vob: { type: 'video/x-ms-vob', charset: null },
  wm: { type: 'video/x-ms-wm', charset: null },
  wmv: { type: 'video/x-ms-wmv', charset: null },
  wmx: { type: 'video/x-ms-wmx', charset: null },
  wvx: { type: 'video/x-ms-wvx', charset: null },
  avi: { type: 'video/x-msvideo', charset: null },
  movie: { type: 'video/x-sgi-movie', charset: null },
  smv: { type: 'video/x-smv', charset: null },
  ice: { type: 'x-conference/x-cooltalk', charset: null }
}

m.inkml = m.ink
m.war = m.jar
m.ear = m.jar
m.map = m.json
m.nb = m.ma
m.mb = m.ma
m.mp21 = m.m21
m.mpg4 = m.mp4
m.mp4s = m.mp4
m.m4p = m.mp4
m.dot = m.doc
m.dms = m.bin
m.lrf = m.bin
m.mar = m.bin
m.so = m.bin
m.dist = m.bin
m.distz = m.bin
m.pkg = m.bin
m.bpk = m.bin
m.dump = m.bin
m.elc = m.bin
m.deploy = m.bin
m.exe = m.bin
m.dll = m.bin
m.deb = m.bin
m.dmg = m.bin
m.iso = m.bin
m.img = m.bin
m.msi = m.bin
m.msp = m.bin
m.msm = m.bin
m.buffer = m.bin
m.onetoc2 = m.onetoc
m.onetmp = m.onetoc
m.onepkg = m.onetoc
m.one = m.onetoc
m.onea = m.onetoc
m.p7c = m.p7m
m.eps = m.ai
m.ps = m.ai
m.owl = m.rdf
m.sieve = m.siv
m.smil = m.smi
m.teicorpus = m.tei
m.acutc = m.atc
m.fxpl = m.fxp
m.c4d = m.c4g
m.c4f = m.c4g
m.c4p = m.c4g
m.c4u = m.c4g
m.uvvf = m.uvf
m.uvd = m.uvf
m.uvvd = m.uvf
m.uvvt = m.uvt
m.uvvx = m.uvx
m.uvvz = m.uvz
m.et3 = m.es3
m.dataless = m.seed
m.frame = m.fm
m.maker = m.fm
m.book = m.fm
m.gre = m.gex
m.gqs = m.gqf
m.listafp = m.afp
m.list3820 = m.afp
m.icm = m.icc
m.xpx = m.xpw
m.ktr = m.ktz
m.kpt = m.kpr
m.kwt = m.kwd
m.knp = m.kne
m.skd = m.skp
m.skt = m.skp
m.skm = m.skp
m.xlm = m.xls
m.xla = m.xls
m.xlc = m.xls
m.xlt = m.xls
m.xlw = m.xls
m.pps = m.ppt
m.pot = m.ppt
m.mpt = m.mpp
m.wks = m.wps
m.wcm = m.wps
m.wdb = m.wps
m.nitf = m.ntf
m.pqa = m.pdb
m.oprc = m.pdb
m.qxt = m.qxd
m.qwd = m.qxd
m.qwt = m.qxd
m.qxl = m.qxd
m.qxb = m.qxd
m.twds = m.twd
m.sdkd = m.sdkm
m.vor = m.sdw
m.susp = m.sus
m.sisx = m.sis
m.cap = m.pcap
m.dmp = m.pcap
m.ufdl = m.ufd
m.uo = m.uoml
m.vst = m.vsd
m.vss = m.vsd
m.vsw = m.vsd
m.vsdx = m.vsd
m.vtx = m.vsd
m.zirz = m.zir
m.x32 = m.aab
m.u32 = m.aab
m.vox = m.aab
m.blorb = m.blb
m.boz = m.bz2
m.cba = m.cbr
m.cbt = m.cbr
m.cbz = m.cbr
m.cb7 = m.cbr
m.udeb = m.deb
m.dcr = m.dir
m.dxr = m.dir
m.cst = m.dir
m.cct = m.dir
m.cxt = m.dir
m.w3d = m.dir
m.fgd = m.dir
m.swa = m.dir
m.pfb = m.pfa
m.pfm = m.pfa
m.afm = m.pfa
m.lha = m.lzh
m.mobi = m.prc
m.com = m.exe
m.bat = m.exe
m.m13 = m.mvb
m.m14 = m.mvb
m.emf = m.wmf
m.emz = m.wmf
m.cdf = m.nc
m.pm = m.pl
m.pfx = m.p12
m.spc = m.p7b
m.tk = m.tcl
m.texi = m.texinfo
m.crt = m.der
m.pem = m.der
m.z2 = m.z1
m.z3 = m.z1
m.z4 = m.z1
m.z5 = m.z1
m.z6 = m.z1
m.z7 = m.z1
m.z8 = m.z1
m.xht = m.xhtml
m.xsl = m.xml
m.xsd = m.xml
m.rng = m.xml
m.xslt = m.xsl
m.xhvml = m.mxml
m.xvml = m.mxml
m.xvm = m.mxml
m.aac = m.adts
m.snd = m.au
m.midi = m.mid
m.kar = m.mid
m.rmi = m.mid
m.mp4a = m.m4a
m.m4b = m.m4a
m.mp2 = m.mpga
m.mp2a = m.mpga
m.m2a = m.mpga
m.m3a = m.mpga
m.ogg = m.oga
m.spx = m.oga
m.opus = m.oga
m.uvva = m.uva
m.aiff = m.aif
m.aifc = m.aif
m.ra = m.ram
m.dib = m.bmp
m.jpg2 = m.jp2
m.jpeg = m.jpg
m.jpe = m.jpg
m.jpgm = m.jpm
m.jpf = m.jpx
m.btf = m.btif
m.svgz = m.svg
m.tiff = m.tif
m.uvvi = m.uvi
m.uvg = m.uvi
m.uvvg = m.uvi
m.djv = m.djvu
m.fhc = m.fh
m.fh4 = m.fh
m.fh5 = m.fh
m.fh7 = m.fh
m.pct = m.pic
m.mime = m.eml
m.mht = m.eml
m.mhtml = m.eml
m.iges = m.igs
m.mesh = m.msh
m.silo = m.msh
m.stp = m.step
m.stpnc = m.step
m.p21 = m.step
m['210'] = m.step
m.pyox = m.pyo
m.vrml = m.wrl
m.x3dbz = m.x3db
m.x3dvz = m.x3dv
m.x3dz = m.x3d
m.manifest = m.appcache
m.ifb = m.ics
m.litcoffee = m.coffee
m.htm = m.html
m.shtml = m.html
m.mjs = m.js
m.markdown = m.md
m.text = m.txt
m.conf = m.txt
m.def = m.txt
m.list = m.txt
m.log = m.txt
m.in = m.txt
m.ini = m.txt
m.sgm = m.sgml
m.slm = m.slim
m.styl = m.stylus
m.tr = m.t
m.roff = m.t
m.man = m.t
m.me = m.t
m.ms = m.t
m.uris = m.uri
m.urls = m.uri
m.asm = m.s
m.cc = m.c
m.cxx = m.c
m.cpp = m.c
m.h = m.c
m.hh = m.c
m.dic = m.c
m.for = m.f
m.f77 = m.f
m.f90 = m.f
m.pas = m.p
m.yml = m.yaml
m.mjp2 = m.mj2
m.m2t = m.ts
m.m2ts = m.ts
m.mp4v = m.mp4
m.mpg = m.mpeg
m.mpe = m.mpeg
m.m1v = m.mpeg
m.m2v = m.mpeg
m.mov = m.qt
m.uvvh = m.uvh
m.uvvm = m.uvm
m.uvvp = m.uvp
m.uvvs = m.uvs
m.uvvv = m.uvv
m.m4u = m.mxu
m.uvvu = m.uvu
m.mk3d = m.mkv
m.mks = m.mkv
m.asx = m.asf

module.exports = function getMimeType (name, charset = true) {
  if (!name) return null
  let e = m[name.slice(name.lastIndexOf('.') + 1).toLowerCase()]
  if (!e) e = m.bin
  return e.type + (charset && e.charset ? '; charset=' + e.charset : '')
}
